### ISSUE TITLE
Include css ootb or make it easier to override

### ISSUE THREAD

**Issue by ulmus** [TriOptima/tri.form#19]
This is related to the issue https://github.com/TriOptima/tri.table/issues/28

The generic problem is that no css file is provided out of the box for forms. Some generic styling should be provided.

Better still, a popular or several popular css frameworks could be supported using some kind of "render style" setting. This would swap out relevant templates.

**Comment by boxed** [comment]
This is coming "soon". Watch this space for some radical new stuff :P

**Comment by boxed** [comment]
This is fixed in [iommi](http://iommi.rocks)
